data:
  dataset: treatment
  batch_size: 32
  test_batch_size: 16
  val_batch_size: 16
  train_set: 0.8
  val_set: 0.2

  time_seires: ["./processed/pre.npy", None]
  t1_root: [None]



  window_width: 200
  window_step: 200
  test_mode: out_test_balanced
  fold: 0

model:

  # gru or cnn 
  extractor_type: gru
  embedding_size: 8 
  window_size: 8 

  cnn_pool_size: 16

  # product or linear
  graph_generation: product

  num_gru_layers: 4

  dropout: 0.5



train:
  # normal or bilevel 
  method: normal
  lr: 1.0e-4 # defaulr 1e-4
  weight_decay: 1.0e-4
  epochs: 500
  optimizer: adam
  seq_len: 100
  node_size: 70

  group_loss: true
  sparsity_loss: true
  sparsity_loss_weight: 1.0e-4
  log_folder: result_local
  
  # uniform or pearson
  pure_gnn_graph: pearson